# Generated by Django 5.0.6 on 2024-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentry", "0711_backfill_group_attributes_to_self_hosted"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="region",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]